import { Card } from "flowbite-react";
import { type NextPage } from "next";
import Head from "next/head";
import NewCarForm from "~/components/garage/newCarForm";
import { api } from "~/utils/api";

const Garage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mon Garage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="m-6 mx-auto text-center text-4xl font-bold text-slate-800">
        Voici votre garage!
      </h1>
      <p className="m-6 mx-auto text-center font-bold text-slate-800">
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea, ratione
        minus non laborum necessitatibus molestias cumque ullam unde optio vitae
        facilis hic officia possimus, nulla temporibus ex quas doloribus alias.
        Quidem cum saepe nam quasi vitae qui recusandae quis itaque. Nisi facere
        laudantium cupiditate reiciendis ad veritatis, animi itaque iure
        delectus debitis ut sed illum eum quo libero aspernatur inventore quasi
        tempore temporibus maxime minima aperiam. Dicta modi animi aperiam!
      </p>
      <CarsInGarage />
    </>
  );
};

function CarsInGarage() {
  const { data: cars, isLoading } = api.garage.getUserGarage.useQuery();
  if (isLoading) {
    return <div>loading...</div>;
  }

  if (!cars || cars.length === 0)
    return (
      <Card className="mx-auto  max-w-2xl ">
        <NewCarForm />
      </Card>
    );

  return (
    <div className="mx-auto flex  flex-col gap-4">
      <div className="grid grid-cols-3 gap-3">
        {[...cars].map((car) => (
          <Card
            href={`/car/${car.id}`}
            key={car.id}
            imgSrc="https://www.willow-car-sales.co.uk/wp-content/uploads/2019/11/placeholder-image-1.jpg"
            className="max-w-sm"
          >
            <h5 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
              {car.make} - {car.model} <small>{car.year}</small>
            </h5>
            <p className="font-normal text-gray-700 dark:text-gray-400">
              {car.mileage} km
            </p>
          </Card>
        ))}
        <Card href="/garage/add">
          <h5 className="mb-2 text-center text-3xl font-bold text-emerald-400 dark:text-white">
            Ajouter une voiture à mon garage
          </h5>
          <p className="mx-auto text-6xl text-green-400">+</p>
        </Card>
      </div>
    </div>
  );
}

//Modals are not working for the moment because of a bug in flowbite-react and NextJS SSR.

// function ModalNewCar() {
//   const [show, setShow] = useState(false);

//   useEffect(() => {
//     setShow(false);
//   }, []);

//   const onClick = () => setShow(true);
//   const onClose = () => setShow(false);

//   return (
//     <>
//       <Button>Toggle modal</Button>
//       <Modal size="xl" popup={true}>
//         <Modal.Header />
//         <Modal.Body>
//           <NewCarForm />
//         </Modal.Body>
//       </Modal>
//     </>
//   );
// }

export default Garage;
