import { type PropsWithChildren } from "react";
import Head from "next/head";
import MainNav from "./navbar";

export const PageLayout = (props: PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Car Report</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainNav />
      <main className="flex h-screen justify-center">
        <div className="h-full w-full max-w-screen-xl">{props.children}</div>
      </main>
    </>
  );
};
